# Generated by Django 5.0.9 on 2024-12-03 05:11

import wagtail.images.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_change_image_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
