# Generated by Django 4.2.17 on 2025-01-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_customrendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='customdocument',
            name='file_size',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
